# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90

# Number of days of inactivity before a stale issue is closed
daysUntilClose: false

# Issues with these labels will never be considered stale
exemptLabels:
  - backlog
  - bug
  - emergency
  - high priority
  - priority
  - project
  - security
  - technical-debt

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. We want to keep it in our todo list but haven't had the time
  to address it yet.
  
  Thank you for your contributions!

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
